image: python:slim

before_script:
- apt-get update
- apt-get install -y build-essential scons pkg-config libx11-dev libxcursor-dev
- apt-get install -y libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev
- apt-get install -y libpulse-dev libfreetype6-dev libudev-dev libxi-dev
- apt-get install -y libxrandr-dev git

pages:
    script:
    - "echo Threads available: $(nproc)"
    - git clone --depth 1 --branch zip-module https://github.com/flyingpimonster/godot.git
    - cd godot
    - scons platform=server debug_symbols=no xaudio2=no pulseaudio=no touch=no module_arkit_enabled=no module_assimp_enabled=no module_camera_enabled=no module_csg_enabled=no module_cvtt_enabled=no module_dds_enabled=no module_enet_enabled=no module_etc_enabled=no module_gdnative_enabled=no module_gridmap_enabled=no module_hdr_enabled=no module_jsonrpc_enabled=no module_mobile_vr_enabled=no module_mono_enabled=no module_ogg_enabled=no module_opensimplex_enabled=no module_opus_enabled=no module_pvr_enabled=no module_recast_enabled=no module_squish_enabled=no module_stb_vorbis_enabled=no module_tga_enabled=no module_theora_enabled=no module_tinyexr_enabled=no module_upnp_enabled=no module_vhacd_enabled=no module_visual_script_enabled=no module_vorbis_enabled=no module_webm_enabled=no module_webp_enabled=no module_webrtc_enabled=no module_websocket_enabled=no module_xatlas_unwrap_enabled=no -j $(nproc)
    - scons target=release platform=x11 debug_symbols=no disable_3d=yes tools=no xaudio2=no pulseaudio=no touch=no module_arkit_enabled=no module_assimp_enabled=no module_bullet_enabled=no module_camera_enabled=no module_csg_enabled=no module_cvtt_enabled=no module_dds_enabled=no module_enet_enabled=no module_etc_enabled=no module_gdnative_enabled=no module_gridmap_enabled=no module_hdr_enabled=no module_jsonrpc_enabled=no module_mobile_vr_enabled=no module_mono_enabled=no module_ogg_enabled=no module_opensimplex_enabled=no module_opus_enabled=no module_pvr_enabled=no module_recast_enabled=no module_squish_enabled=no module_stb_vorbis_enabled=no module_tga_enabled=no module_theora_enabled=no module_tinyexr_enabled=no module_upnp_enabled=no module_vhacd_enabled=no module_visual_script_enabled=no module_vorbis_enabled=no module_webm_enabled=no module_webp_enabled=no module_webrtc_enabled=no module_websocket_enabled=no module_xatlas_unwrap_enabled=no -j $(nproc)
    - mkdir -p $HOME/.local/share/godot/templates/3.2.beta
    - cp bin/godot.x11.opt.64 $HOME/.local/share/godot/templates/3.2.beta/linux_x11_64_release
    - cd -
    - ./godot/bin/godot_server.x11.tools.64 --export linux hourglass-linux
    - mkdir public
    - tar czf public/hourglass-linux.tar.gz hourglass-linux

    only:
    - tags

    artifacts:
        paths:
        - public

